name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Upload files to EC2
    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "."
        target: "/var/www/laravel"

    # Step 3: Run commands on EC2
    - name: Run Commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/laravel

          # Install Composer dependencies
          composer install --no-dev --optimize-autoloader

          # Copy .env file
          cp .env.example .env

          # Generate application key
          php artisan key:generate

          # Run migrations
          php artisan migrate --force

          # Clear and cache configurations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Set permissions
          sudo chown -R www-data:www-data /var/www/laravel
          sudo chmod -R 755 /var/www/laravel
          sudo chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache
