name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "."
        target: "/var/www/laravel"

    - name: Run Migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/laravel
          php artisan migrate --force

    - name: Clear Cache
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/laravel
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
