name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Upload files to EC2
    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "."
        target: "/var/www/laravel"

    # Step 3: Run commands on EC2
    - name: Run Commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/laravel

          # Install Composer dependencies
          composer install --no-dev --optimize-autoloader

          # Copy .env file
          cp .env.example .env

          # Generate application key
          php artisan key:generate

          # Install MySQL/MariaDB if not already installed
          sudo apt update
          sudo apt install -y mysql-server

          # Start and enable MySQL
          sudo systemctl start mysql
          sudo systemctl enable mysql

          # Secure MySQL installation (optional)
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '12345678';"
          sudo mysql -e "DELETE FROM mysql.user WHERE User='';"
          sudo mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
          sudo mysql -e "DROP DATABASE IF EXISTS test;"
          sudo mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
          sudo mysql -e "FLUSH PRIVILEGES;"

          # Create database and user
          sudo mysql -u root -p"12345678" -e "CREATE DATABASE IF NOT EXISTS laravel;"
          sudo mysql -u root -p"12345678" -e "CREATE USER IF NOT EXISTS 'laravel_user'@'localhost' IDENTIFIED BY '12345678';"
          sudo mysql -u root -p"12345678" -e "GRANT ALL PRIVILEGES ON laravel.* TO 'laravel_user'@'localhost';"
          sudo mysql -u root -p"12345678" -e "FLUSH PRIVILEGES;"

          # Update .env file with database credentials
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=laravel/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=laravel_user/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=12345678/" .env

          # Run migrations
          php artisan migrate --force

          # Clear and cache configurations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Set permissions
          sudo chown -R www-data:www-data /var/www/laravel
          sudo chmod -R 755 /var/www/laravel
          sudo chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache
          #testagain
